### ISSUE TITLE
Using pseudo handle to bypass SACL is not nessesary

### ISSUE THREAD

**Issue by EddieIvan01** [codewhitesec/SysmonEnte#1]
According to my testing, the bug of `NtDuplicateObject` seems to be fixed. So the code following is not nessesary:

```c++
ntStatus = NtDuplicateObject(hduppriv, NtCurrentProcess(), NtCurrentProcess(), &hhighpriv, PROCESS_ALL_ACCESS, FALSE, 0);
```

To bypass sysmon event 10 audit, just open its handle as `QUERY_LIMITED_INFORMATION` then duplicate to a `ALL_ACCESS` new one. It works well and only generate `QUERY_LIMITED_INFORMATION` log.

**Comment by theLangsam** [comment]
If you want to generate a low process access event (10) in sysmon and want to elevate the handle, you can do it as you write.

You can see this for example in the Handle Elevation section of the blogpost.
https://codewhitesec.blogspot.com/2022/09/attacks-on-sysmon-revisited-sysmonente.html
```HANDLE hSysmon = NULL;
HANDLE hhighpriv = NULL;
BOOL bsuccess = FALSE;

hSysmon = OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, FALSE, 3340);
bsuccess = DuplicateHandle(GetCurrentProcess(), hSysmon, GetCurrentProcess(), &hhighpriv, PROCESS_ALL_ACCESS, FALSE, 0);
```

But if your target has configured a SACL with for example PROCESS_VM_WRITE, and has activated object access auditing via GPO, you will also trigger an 4656 Event in the Windows Security Event Log.

In order to bypass that 4656 event with a configured SACL, you can use James Forshaw's method. Then you will only get a 4656 event when you have configured a SACL for at least PROCESS_DUP_HANDLE.

You can use the tool in the folder SACLProtect in order to set a SACL for sysmon and test with the SACL detections.

**Comment by EddieIvan01** [comment]
Thanks for replying. I got you point. But still some questions:

Q1.

> This only works if the targeted process runs as the same user as the duplicating process.

Is there any documents about this? (I didn't find)

Q2.

So if I understand correctly, just using handle elevation will triger the access auditing, because the access rights is elevated so audit function will be called. James Forshaw's method doesn't, because the bug of duplicate function grants all access directly, as so it bypasses the access check.

**Comment by theLangsam** [comment]
For Question 1:

We could not find any documentation by Microsoft. This was found out by just playing with the duplicate handle function and realizing that we can duplicate a handle for the same source user but not for a different process, even when we had the SE_DEBUG Privilege is enabled. Finally, we realized that handle elevation for a system process is working when we run as the same user.

Question 2:

In default there is no object access auditing active. In a default environment you have to enable it via GPO. On default Sysmon has no SACL, even when object access auditing is active. So if you use handle elevation without the SACL bypass on a default windows machine, you will not get the event id 4656.

If object access auditing is configured for PROCESS_VM_READ, Handle Elevation elevate the handle to the PROCESS_DUP_HANDLE right, because no PROCESS_VM_READ access was requested. So no log entry is generated.

You still can set up a SACL to detect PROCESS_DUP_HANDLE access on Sysmon and then you will see a 4656 event for Handle Elevation with the SACL Bypass.

If you are interested how the SACL Bypass by James Forshaw works, I recommend you this ressource:
https://www.tiraniddo.dev/2017/10/bypassing-sacl-auditing-on-lsass.html?m=1

**Comment by EddieIvan01** [comment]
Got it, thx
